name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: pip install pylint flake8
    - name: PyLint 
      run: pylint main.py
    - name: Flake8
      run: flake8 main.py

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Test
      run: python -m --verbose --failfast unittest test.py

  build:
    name: Build and Store Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build
      run: python main.py 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    env:
      user: ${{ secrets.USER }}
      password: ${{ secrets.PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: output
    - name: Deploy
      run: curl -v --stderr deploy.log -w "%{http_code}\n" -F password=<password> -F file=@build/index.html -F user=<user> https://cs.uns.edu.ar/~jose.moyano/index.php
    - name: Check Log
      run: grep -q 'http_code": 200' deploy.log || echo "Error: HTTP code is not 200"